<?xml version="1.0" encoding="utf-8"?><Database Name="ImprintCMS" Class="ImprintCMSDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\sqlexpress;Initial Catalog=ImprintCMS;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="ImprintCMSConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Article" Member="Articles">
    <Type Name="Article">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="IsVisible" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ImageId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PersonId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BookId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsForContactPage" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Book_Article" Member="Book" ThisKey="BookId" OtherKey="Id" Type="Book" IsForeignKey="true" />
      <Association Name="Person_Article" Member="Person" ThisKey="PersonId" OtherKey="Id" Type="Person" IsForeignKey="true" />
      <Association Name="UploadedFile_Article" Member="UploadedFile" ThisKey="ImageId" OtherKey="Id" Type="UploadedFile" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Binding" Member="Bindings">
    <Type Name="Binding">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Binding_Edition" Member="Editions" ThisKey="Id" OtherKey="BindingId" Type="Edition" />
    </Type>
  </Table>
  <Table Name="dbo.Book" Member="Books">
    <Type Name="Book">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Subtitle" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IsVisible" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Quotes" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ExcerptId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GenreId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IsDebut" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ExternalPublisher" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ExternalReleaseYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Book_Article" Member="Articles" ThisKey="Id" OtherKey="BookId" Type="Article" />
      <Association Name="Book_Edition" Member="Editions" ThisKey="Id" OtherKey="BookId" Type="Edition" />
      <Association Name="Book_Relation" Member="Relations" ThisKey="Id" OtherKey="BookId" Type="Relation" />
      <Association Name="Genre_Book" Member="Genre" ThisKey="GenreId" OtherKey="Id" Type="Genre" IsForeignKey="true" />
      <Association Name="UploadedFile_Book" Member="UploadedFile" ThisKey="ExcerptId" OtherKey="Id" Type="UploadedFile" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.BookList" Member="BookLists">
    <Type Name="BookList">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="IsVisible" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="SequenceIdentifier" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="BookList_BookListMembership" Member="BookListMemberships" ThisKey="Id" OtherKey="BookListId" Type="BookListMembership" />
    </Type>
  </Table>
  <Table Name="dbo.BookListMembership" Member="BookListMemberships">
    <Type Name="BookListMembership">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="EditionId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BookListId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SequenceIdentifier" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="BookList_BookListMembership" Member="BookList" ThisKey="BookListId" OtherKey="Id" Type="BookList" IsForeignKey="true" />
      <Association Name="Edition_BookListMembership" Member="Edition" ThisKey="EditionId" OtherKey="Id" Type="Edition" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ContactArticle" Member="ContactArticles">
    <Type Name="ContactArticle">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="BodyText" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SequenceIdentifier" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Edition" Member="Editions">
    <Type Name="Edition">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Number" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Isbn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PageCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsForSale" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ReleaseDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="BindingId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SmallCoverId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LargeCoverId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BookId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(9,2)" CanBeNull="true" />
      <Association Name="Edition_BookListMembership" Member="BookListMemberships" ThisKey="Id" OtherKey="EditionId" Type="BookListMembership" />
      <Association Name="Binding_Edition" Member="Binding" ThisKey="BindingId" OtherKey="Id" Type="Binding" IsForeignKey="true" />
      <Association Name="Book_Edition" Member="Book" ThisKey="BookId" OtherKey="Id" Type="Book" IsForeignKey="true" />
      <Association Name="UploadedFile_Edition" Member="UploadedFile" ThisKey="SmallCoverId" OtherKey="Id" Type="UploadedFile" IsForeignKey="true" />
      <Association Name="UploadedFile_Edition1" Member="UploadedFile1" ThisKey="LargeCoverId" OtherKey="Id" Type="UploadedFile" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Genre" Member="Genres">
    <Type Name="Genre">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="SequenceIdentifier" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Genre_Book" Member="Books" ThisKey="Id" OtherKey="GenreId" Type="Book" />
    </Type>
  </Table>
  <Table Name="dbo.Person" Member="Persons">
    <Type Name="Person">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Awards" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Translations" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Anthologies" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="SmallImageId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LargeImageId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PhotographerCredit" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsVisible" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="HasPage" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Person_Article" Member="Articles" ThisKey="Id" OtherKey="PersonId" Type="Article" />
      <Association Name="Person_Relation" Member="Relations" ThisKey="Id" OtherKey="PersonId" Type="Relation" />
      <Association Name="UploadedFile_Person" Member="UploadedFile" ThisKey="SmallImageId" OtherKey="Id" Type="UploadedFile" IsForeignKey="true" />
      <Association Name="UploadedFile_Person1" Member="UploadedFile1" ThisKey="LargeImageId" OtherKey="Id" Type="UploadedFile" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Relation" Member="Relations">
    <Type Name="Relation">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BookId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PersonId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="SequenceIdentifier" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Book_Relation" Member="Book" ThisKey="BookId" OtherKey="Id" Type="Book" IsForeignKey="true" />
      <Association Name="Person_Relation" Member="Person" ThisKey="PersonId" OtherKey="Id" Type="Person" IsForeignKey="true" />
      <Association Name="Role_Relation" Member="Role" ThisKey="RoleId" OtherKey="Id" Type="Role" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Role" Member="Roles">
    <Type Name="Role">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ShortName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Role_Relation" Member="Relations" ThisKey="Id" OtherKey="RoleId" Type="Relation" />
    </Type>
  </Table>
  <Table Name="dbo.UploadedFile" Member="UploadedFiles">
    <Type Name="UploadedFile">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FileName" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="ContentType" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Data" Type="System.Data.Linq.Binary" DbType="VarBinary(MAX) NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="Category" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ContentLength" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="UploadedFile_Article" Member="Articles" ThisKey="Id" OtherKey="ImageId" Type="Article" />
      <Association Name="UploadedFile_Book" Member="Books" ThisKey="Id" OtherKey="ExcerptId" Type="Book" />
      <Association Name="UploadedFile_Edition" Member="Editions" ThisKey="Id" OtherKey="SmallCoverId" Type="Edition" />
      <Association Name="UploadedFile_Edition1" Member="Editions1" ThisKey="Id" OtherKey="LargeCoverId" Type="Edition" />
      <Association Name="UploadedFile_Person" Member="Persons" ThisKey="Id" OtherKey="SmallImageId" Type="Person" />
      <Association Name="UploadedFile_Person1" Member="Persons1" ThisKey="Id" OtherKey="LargeImageId" Type="Person" />
    </Type>
  </Table>
</Database>