//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImprintCMS.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Phrases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Phrases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImprintCMS.App_GlobalResources.Phrases", typeof(Phrases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p style=&quot;font-family: sans-serif;&quot;&gt;{0}&lt;/p&gt;.
        /// </summary>
        public static string EmailBodyWrapper {
            get {
                return ResourceManager.GetString("EmailBodyWrapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stylesheet.
        /// </summary>
        public static string FileTypeCss {
            get {
                return ResourceManager.GetString("FileTypeCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string FileTypeImage {
            get {
                return ResourceManager.GetString("FileTypeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Javascript.
        /// </summary>
        public static string FileTypeJavascript {
            get {
                return ResourceManager.GetString("FileTypeJavascript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy stylesheet.
        /// </summary>
        public static string FileTypeLegacyCss {
            get {
                return ResourceManager.GetString("FileTypeLegacyCss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF.
        /// </summary>
        public static string FileTypePDF {
            get {
                return ResourceManager.GetString("FileTypePDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word document.
        /// </summary>
        public static string FileTypeWordDocument {
            get {
                return ResourceManager.GetString("FileTypeWordDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anthology contributions.
        /// </summary>
        public static string LabelAnthologies {
            get {
                return ResourceManager.GetString("LabelAnthologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        public static string LabelArticle {
            get {
                return ResourceManager.GetString("LabelArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tab.
        /// </summary>
        public static string LabelArticleGroup {
            get {
                return ResourceManager.GetString("LabelArticleGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        public static string LabelArticles {
            get {
                return ResourceManager.GetString("LabelArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio excerpt.
        /// </summary>
        public static string LabelAudioExcerpt {
            get {
                return ResourceManager.GetString("LabelAudioExcerpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awards.
        /// </summary>
        public static string LabelAwards {
            get {
                return ResourceManager.GetString("LabelAwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to {0}.
        /// </summary>
        public static string LabelBackTo {
            get {
                return ResourceManager.GetString("LabelBackTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding.
        /// </summary>
        public static string LabelBinding {
            get {
                return ResourceManager.GetString("LabelBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body text.
        /// </summary>
        public static string LabelBodyText {
            get {
                return ResourceManager.GetString("LabelBodyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        public static string LabelBook {
            get {
                return ResourceManager.GetString("LabelBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string LabelBookDeliveryFormat {
            get {
                return ResourceManager.GetString("LabelBookDeliveryFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supports download.
        /// </summary>
        public static string LabelBookDeliveryFormatDownloadSupported {
            get {
                return ResourceManager.GetString("LabelBookDeliveryFormatDownloadSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supports ebook.
        /// </summary>
        public static string LabelBookDeliveryFormatEbookSupported {
            get {
                return ResourceManager.GetString("LabelBookDeliveryFormatEbookSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supports physical.
        /// </summary>
        public static string LabelBookDeliveryFormatPhysicalSupported {
            get {
                return ResourceManager.GetString("LabelBookDeliveryFormatPhysicalSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formats.
        /// </summary>
        public static string LabelBookDeliveryFormats {
            get {
                return ResourceManager.GetString("LabelBookDeliveryFormats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book list.
        /// </summary>
        public static string LabelBookList {
            get {
                return ResourceManager.GetString("LabelBookList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string LabelBooks {
            get {
                return ResourceManager.GetString("LabelBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width of cached cover images (in pixels).
        /// </summary>
        public static string LabelCachedCoverWidth {
            get {
                return ResourceManager.GetString("LabelCachedCoverWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width of cached portrait images (in pixels).
        /// </summary>
        public static string LabelCachedPortraitWidth {
            get {
                return ResourceManager.GetString("LabelCachedPortraitWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string LabelCancel {
            get {
                return ResourceManager.GetString("LabelCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        public static string LabelContactArticles {
            get {
                return ResourceManager.GetString("LabelContactArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cover image download notice.
        /// </summary>
        public static string LabelCoverImageDownloadNotice {
            get {
                return ResourceManager.GetString("LabelCoverImageDownloadNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string LabelCreate {
            get {
                return ResourceManager.GetString("LabelCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string LabelDate {
            get {
                return ResourceManager.GetString("LabelDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string LabelDelete {
            get {
                return ResourceManager.GetString("LabelDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete all.
        /// </summary>
        public static string LabelDeleteAll {
            get {
                return ResourceManager.GetString("LabelDeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete.
        /// </summary>
        public static string LabelDeleteConfirmationPrefix {
            get {
                return ResourceManager.GetString("LabelDeleteConfirmationPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        public static string LabelDeleteConfirmationSuffix {
            get {
                return ResourceManager.GetString("LabelDeleteConfirmationSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please remove any dependencies before attempting to delete this element..
        /// </summary>
        public static string LabelDeleteDependenciesGeneral {
            get {
                return ResourceManager.GetString("LabelDeleteDependenciesGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please remove any dependencies before attempting to delete.
        /// </summary>
        public static string LabelDeleteDependenciesPrefix {
            get {
                return ResourceManager.GetString("LabelDeleteDependenciesPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to :.
        /// </summary>
        public static string LabelDeleteDependenciesSuffix {
            get {
                return ResourceManager.GetString("LabelDeleteDependenciesSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string LabelDescription {
            get {
                return ResourceManager.GetString("LabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide from front page.
        /// </summary>
        public static string LabelDontShowOnFrontPage {
            get {
                return ResourceManager.GetString("LabelDontShowOnFrontPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop to sort.
        /// </summary>
        public static string LabelDragAndDropToSort {
            get {
                return ResourceManager.GetString("LabelDragAndDropToSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional edition info.
        /// </summary>
        public static string LabelEditionAdditionalInfo {
            get {
                return ResourceManager.GetString("LabelEditionAdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing blurb (shown in front page book lists).
        /// </summary>
        public static string LabelEditionBlurb {
            get {
                return ResourceManager.GetString("LabelEditionBlurb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book editions.
        /// </summary>
        public static string LabelEditions {
            get {
                return ResourceManager.GetString("LabelEditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excerpt.
        /// </summary>
        public static string LabelExcerpt {
            get {
                return ResourceManager.GetString("LabelExcerpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other publisher.
        /// </summary>
        public static string LabelExternalPublisher {
            get {
                return ResourceManager.GetString("LabelExternalPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release year (if released by other publisher).
        /// </summary>
        public static string LabelExternalReleaseYear {
            get {
                return ResourceManager.GetString("LabelExternalReleaseYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files with names starting with &apos;favicon&apos; will be served as icons in site markup..
        /// </summary>
        public static string LabelFaviconLegend {
            get {
                return ResourceManager.GetString("LabelFaviconLegend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string LabelFileActions {
            get {
                return ResourceManager.GetString("LabelFileActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string LabelFileCategory {
            get {
                return ResourceManager.GetString("LabelFileCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File name.
        /// </summary>
        public static string LabelFileName {
            get {
                return ResourceManager.GetString("LabelFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string LabelFileSize {
            get {
                return ResourceManager.GetString("LabelFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string LabelFileType {
            get {
                return ResourceManager.GetString("LabelFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string LabelFirstName {
            get {
                return ResourceManager.GetString("LabelFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string LabelGenre {
            get {
                return ResourceManager.GetString("LabelGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Analytics tracking code.
        /// </summary>
        public static string LabelGoogleAnalyticsTrackingCode {
            get {
                return ResourceManager.GetString("LabelGoogleAnalyticsTrackingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other publisher.
        /// </summary>
        public static string LabelHasExternalPublisher {
            get {
                return ResourceManager.GetString("LabelHasExternalPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show with own page on site.
        /// </summary>
        public static string LabelHasPage {
            get {
                return ResourceManager.GetString("LabelHasPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide edition number on site.
        /// </summary>
        public static string LabelHideEditionNumber {
            get {
                return ResourceManager.GetString("LabelHideEditionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string LabelHref {
            get {
                return ResourceManager.GetString("LabelHref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TinyMCE API key.
        /// </summary>
        public static string LabelHtmlEditorApiKey {
            get {
                return ResourceManager.GetString("LabelHtmlEditorApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string LabelImage {
            get {
                return ResourceManager.GetString("LabelImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        public static string LabelImages {
            get {
                return ResourceManager.GetString("LabelImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string LabelIsActive {
            get {
                return ResourceManager.GetString("LabelIsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN.
        /// </summary>
        public static string LabelIsbn {
            get {
                return ResourceManager.GetString("LabelIsbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debut.
        /// </summary>
        public static string LabelIsDebut {
            get {
                return ResourceManager.GetString("LabelIsDebut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For sale.
        /// </summary>
        public static string LabelIsForSale {
            get {
                return ResourceManager.GetString("LabelIsForSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t show on site.
        /// </summary>
        public static string LabelIsNotVisible {
            get {
                return ResourceManager.GetString("LabelIsNotVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show on site.
        /// </summary>
        public static string LabelIsVisible {
            get {
                return ResourceManager.GetString("LabelIsVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string LabelLargeImage {
            get {
                return ResourceManager.GetString("LabelLargeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LabelLastName {
            get {
                return ResourceManager.GetString("LabelLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to book.
        /// </summary>
        public static string LabelLinkToBook {
            get {
                return ResourceManager.GetString("LabelLinkToBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link to person.
        /// </summary>
        public static string LabelLinkToPerson {
            get {
                return ResourceManager.GetString("LabelLinkToPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out {0}.
        /// </summary>
        public static string LabelLogOut {
            get {
                return ResourceManager.GetString("LabelLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LabelLogOutSimple {
            get {
                return ResourceManager.GetString("LabelLogOutSimple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main content.
        /// </summary>
        public static string LabelMainContent {
            get {
                return ResourceManager.GetString("LabelMainContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string LabelNumber {
            get {
                return ResourceManager.GetString("LabelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of pages.
        /// </summary>
        public static string LabelPageCount {
            get {
                return ResourceManager.GetString("LabelPageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        public static string LabelPeople {
            get {
                return ResourceManager.GetString("LabelPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string LabelPerson {
            get {
                return ResourceManager.GetString("LabelPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person image download notice.
        /// </summary>
        public static string LabelPersonImageDownloadNotice {
            get {
                return ResourceManager.GetString("LabelPersonImageDownloadNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other information (no default heading on site).
        /// </summary>
        public static string LabelPersonMiscInfo {
            get {
                return ResourceManager.GetString("LabelPersonMiscInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photographer.
        /// </summary>
        public static string LabelPhotographerCredit {
            get {
                return ResourceManager.GetString("LabelPhotographerCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string LabelPrice {
            get {
                return ResourceManager.GetString("LabelPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review quotes.
        /// </summary>
        public static string LabelQuotes {
            get {
                return ResourceManager.GetString("LabelQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rights holders.
        /// </summary>
        public static string LabelRelations {
            get {
                return ResourceManager.GetString("LabelRelations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release date.
        /// </summary>
        public static string LabelReleaseDate {
            get {
                return ResourceManager.GetString("LabelReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string LabelRemove {
            get {
                return ResourceManager.GetString("LabelRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        public static string LabelRemoveConfirmationMiddlePart {
            get {
                return ResourceManager.GetString("LabelRemoveConfirmationMiddlePart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove.
        /// </summary>
        public static string LabelRemoveConfirmationPrefix {
            get {
                return ResourceManager.GetString("LabelRemoveConfirmationPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        public static string LabelRemoveConfirmationSuffix {
            get {
                return ResourceManager.GetString("LabelRemoveConfirmationSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        public static string LabelReplace {
            get {
                return ResourceManager.GetString("LabelReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string LabelRole {
            get {
                return ResourceManager.GetString("LabelRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading for book listing on person page.
        /// </summary>
        public static string LabelRoleBookListHeading {
            get {
                return ResourceManager.GetString("LabelRoleBookListHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show book listing on person page.
        /// </summary>
        public static string LabelRoleShowBookList {
            get {
                return ResourceManager.GetString("LabelRoleShowBookList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string LabelSave {
            get {
                return ResourceManager.GetString("LabelSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Søk.
        /// </summary>
        public static string LabelSearch {
            get {
                return ResourceManager.GetString("LabelSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string LabelSelectFile {
            get {
                return ResourceManager.GetString("LabelSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short version.
        /// </summary>
        public static string LabelShortName {
            get {
                return ResourceManager.GetString("LabelShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show on front page.
        /// </summary>
        public static string LabelShowOnFrontPage {
            get {
                return ResourceManager.GetString("LabelShowOnFrontPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string LabelSiteConfigurations {
            get {
                return ResourceManager.GetString("LabelSiteConfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer.
        /// </summary>
        public static string LabelSiteFooter {
            get {
                return ResourceManager.GetString("LabelSiteFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of web site.
        /// </summary>
        public static string LabelSiteName {
            get {
                return ResourceManager.GetString("LabelSiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string LabelSubmit {
            get {
                return ResourceManager.GetString("LabelSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LabelSubmitLogin {
            get {
                return ResourceManager.GetString("LabelSubmitLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle.
        /// </summary>
        public static string LabelSubtitle {
            get {
                return ResourceManager.GetString("LabelSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supporting content.
        /// </summary>
        public static string LabelSupportingContent {
            get {
                return ResourceManager.GetString("LabelSupportingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string LabelTitle {
            get {
                return ResourceManager.GetString("LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translated works.
        /// </summary>
        public static string LabelTranslations {
            get {
                return ResourceManager.GetString("LabelTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All {0} files in {1}.
        /// </summary>
        public static string LabelUploadCategoryFileCount {
            get {
                return ResourceManager.GetString("LabelUploadCategoryFileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part of URL after ISBN.
        /// </summary>
        public static string LabelUrlPostfix {
            get {
                return ResourceManager.GetString("LabelUrlPostfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part of URL before ISBN.
        /// </summary>
        public static string LabelUrlPrefix {
            get {
                return ResourceManager.GetString("LabelUrlPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string LabelUsername {
            get {
                return ResourceManager.GetString("LabelUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this page can not be displayed.
        /// </summary>
        public static string MessageUnhandledException {
            get {
                return ResourceManager.GetString("MessageUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string PagenameAdmin {
            get {
                return ResourceManager.GetString("PagenameAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu tabs.
        /// </summary>
        public static string PagenameArticleGroups {
            get {
                return ResourceManager.GetString("PagenameArticleGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        public static string PagenameArticles {
            get {
                return ResourceManager.GetString("PagenameArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bindings.
        /// </summary>
        public static string PagenameBindings {
            get {
                return ResourceManager.GetString("PagenameBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book lists.
        /// </summary>
        public static string PagenameBookLists {
            get {
                return ResourceManager.GetString("PagenameBookLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string PagenameBooks {
            get {
                return ResourceManager.GetString("PagenameBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurations.
        /// </summary>
        public static string PagenameConfigurations {
            get {
                return ResourceManager.GetString("PagenameConfigurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New article.
        /// </summary>
        public static string PagenameCreateArticle {
            get {
                return ResourceManager.GetString("PagenameCreateArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New tab.
        /// </summary>
        public static string PagenameCreateArticleGroup {
            get {
                return ResourceManager.GetString("PagenameCreateArticleGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New binding.
        /// </summary>
        public static string PagenameCreateBinding {
            get {
                return ResourceManager.GetString("PagenameCreateBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New book.
        /// </summary>
        public static string PagenameCreateBook {
            get {
                return ResourceManager.GetString("PagenameCreateBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New link to book.
        /// </summary>
        public static string PagenameCreateBookLink {
            get {
                return ResourceManager.GetString("PagenameCreateBookLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New book list.
        /// </summary>
        public static string PagenameCreateBookList {
            get {
                return ResourceManager.GetString("PagenameCreateBookList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New book list member.
        /// </summary>
        public static string PagenameCreateBookListMembership {
            get {
                return ResourceManager.GetString("PagenameCreateBookListMembership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New configuration.
        /// </summary>
        public static string PagenameCreateConfiguration {
            get {
                return ResourceManager.GetString("PagenameCreateConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New article.
        /// </summary>
        public static string PagenameCreateContactArticle {
            get {
                return ResourceManager.GetString("PagenameCreateContactArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New book edition.
        /// </summary>
        public static string PagenameCreateEdition {
            get {
                return ResourceManager.GetString("PagenameCreateEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New external store.
        /// </summary>
        public static string PagenameCreateExternalStore {
            get {
                return ResourceManager.GetString("PagenameCreateExternalStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New genre.
        /// </summary>
        public static string PagenameCreateGenre {
            get {
                return ResourceManager.GetString("PagenameCreateGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New image.
        /// </summary>
        public static string PagenameCreateImage {
            get {
                return ResourceManager.GetString("PagenameCreateImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New shortcut.
        /// </summary>
        public static string PagenameCreateMenuShortcut {
            get {
                return ResourceManager.GetString("PagenameCreateMenuShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New person.
        /// </summary>
        public static string PagenameCreatePerson {
            get {
                return ResourceManager.GetString("PagenameCreatePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New link to person.
        /// </summary>
        public static string PagenameCreatePersonLink {
            get {
                return ResourceManager.GetString("PagenameCreatePersonLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New rights holder.
        /// </summary>
        public static string PagenameCreateRelation {
            get {
                return ResourceManager.GetString("PagenameCreateRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New role.
        /// </summary>
        public static string PagenameCreateRole {
            get {
                return ResourceManager.GetString("PagenameCreateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New file.
        /// </summary>
        public static string PagenameCreateUpload {
            get {
                return ResourceManager.GetString("PagenameCreateUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string PagenameDelete {
            get {
                return ResourceManager.GetString("PagenameDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete image.
        /// </summary>
        public static string PagenameDeleteImage {
            get {
                return ResourceManager.GetString("PagenameDeleteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit article.
        /// </summary>
        public static string PagenameEditArticle {
            get {
                return ResourceManager.GetString("PagenameEditArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit tab.
        /// </summary>
        public static string PagenameEditArticleGroup {
            get {
                return ResourceManager.GetString("PagenameEditArticleGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit binding.
        /// </summary>
        public static string PagenameEditBinding {
            get {
                return ResourceManager.GetString("PagenameEditBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit book.
        /// </summary>
        public static string PagenameEditBook {
            get {
                return ResourceManager.GetString("PagenameEditBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit book list.
        /// </summary>
        public static string PagenameEditBookList {
            get {
                return ResourceManager.GetString("PagenameEditBookList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit configuration.
        /// </summary>
        public static string PagenameEditConfiguration {
            get {
                return ResourceManager.GetString("PagenameEditConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit article.
        /// </summary>
        public static string PagenameEditContactArticle {
            get {
                return ResourceManager.GetString("PagenameEditContactArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit book edition.
        /// </summary>
        public static string PagenameEditEdition {
            get {
                return ResourceManager.GetString("PagenameEditEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit external store.
        /// </summary>
        public static string PagenameEditExternalStore {
            get {
                return ResourceManager.GetString("PagenameEditExternalStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit genre.
        /// </summary>
        public static string PagenameEditGenre {
            get {
                return ResourceManager.GetString("PagenameEditGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit image.
        /// </summary>
        public static string PagenameEditImage {
            get {
                return ResourceManager.GetString("PagenameEditImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit menu shortcut.
        /// </summary>
        public static string PagenameEditMenuShortcut {
            get {
                return ResourceManager.GetString("PagenameEditMenuShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit person.
        /// </summary>
        public static string PagenameEditPerson {
            get {
                return ResourceManager.GetString("PagenameEditPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit rights holder.
        /// </summary>
        public static string PagenameEditRelation {
            get {
                return ResourceManager.GetString("PagenameEditRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit role.
        /// </summary>
        public static string PagenameEditRole {
            get {
                return ResourceManager.GetString("PagenameEditRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string PagenameError {
            get {
                return ResourceManager.GetString("PagenameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External stores.
        /// </summary>
        public static string PagenameExternalStores {
            get {
                return ResourceManager.GetString("PagenameExternalStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genres.
        /// </summary>
        public static string PagenameGenres {
            get {
                return ResourceManager.GetString("PagenameGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string PagenameLogIn {
            get {
                return ResourceManager.GetString("PagenameLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu shortcuts.
        /// </summary>
        public static string PagenameMenuShortcuts {
            get {
                return ResourceManager.GetString("PagenameMenuShortcuts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        public static string PagenamePersons {
            get {
                return ResourceManager.GetString("PagenamePersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string PagenameRemove {
            get {
                return ResourceManager.GetString("PagenameRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string PagenameRoles {
            get {
                return ResourceManager.GetString("PagenameRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string PagenameUploads {
            get {
                return ResourceManager.GetString("PagenameUploads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprint CMS.
        /// </summary>
        public static string SystemName {
            get {
                return ResourceManager.GetString("SystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View site.
        /// </summary>
        public static string SystemViewSite {
            get {
                return ResourceManager.GetString("SystemViewSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bytes.
        /// </summary>
        public static string UnitBytesPlural {
            get {
                return ResourceManager.GetString("UnitBytesPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to byte.
        /// </summary>
        public static string UnitBytesSingular {
            get {
                return ResourceManager.GetString("UnitBytesSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to files.
        /// </summary>
        public static string UnitFilesPlural {
            get {
                return ResourceManager.GetString("UnitFilesPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file.
        /// </summary>
        public static string UnitFilesSingular {
            get {
                return ResourceManager.GetString("UnitFilesSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kB.
        /// </summary>
        public static string UnitKiloBytesShort {
            get {
                return ResourceManager.GetString("UnitKiloBytesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        public static string UnitMegaBytesShort {
            get {
                return ResourceManager.GetString("UnitMegaBytesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string UnitNo {
            get {
                return ResourceManager.GetString("UnitNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string UnitYes {
            get {
                return ResourceManager.GetString("UnitYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during an AJAX operation. Please reload the page to see its current state..
        /// </summary>
        public static string ValidationAjaxError {
            get {
                return ResourceManager.GetString("ValidationAjaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file or file is empty.
        /// </summary>
        public static string ValidationEmptyOrNoFile {
            get {
                return ResourceManager.GetString("ValidationEmptyOrNoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release year must be specified for other publishers.
        /// </summary>
        public static string ValidationExternalReleaseYear {
            get {
                return ResourceManager.GetString("ValidationExternalReleaseYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file with this name already exists in this category. Delete old file first if you want to replace it, or use the Replace link..
        /// </summary>
        public static string ValidationFileExists {
            get {
                return ResourceManager.GetString("ValidationFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is too large (max 10 MB).
        /// </summary>
        public static string ValidationFileTooLarge {
            get {
                return ResourceManager.GetString("ValidationFileTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username/password.
        /// </summary>
        public static string ValidationInvalidLogin {
            get {
                return ResourceManager.GetString("ValidationInvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No editions.
        /// </summary>
        public static string ValidationNoEditions {
            get {
                return ResourceManager.GetString("ValidationNoEditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books from other publishers do not have editions.
        /// </summary>
        public static string ValidationNoEditionsForExternalPublisher {
            get {
                return ResourceManager.GetString("ValidationNoEditionsForExternalPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rights holders.
        /// </summary>
        public static string ValidationNoRightsHolders {
            get {
                return ResourceManager.GetString("ValidationNoRightsHolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This person is already a rights holder to this book.
        /// </summary>
        public static string ValidationPersonHasRelationToBook {
            get {
                return ResourceManager.GetString("ValidationPersonHasRelationToBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string ValidationRequiredDefault {
            get {
                return ResourceManager.GetString("ValidationRequiredDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max 50 characters.
        /// </summary>
        public static string ValidationStringLength50 {
            get {
                return ResourceManager.GetString("ValidationStringLength50", resourceCulture);
            }
        }
    }
}
