//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.530
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImprintCMS.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Phrases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Phrases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImprintCMS.App_GlobalResources.Phrases", typeof(Phrases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string FileTypeImage {
            get {
                return ResourceManager.GetString("FileTypeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF.
        /// </summary>
        public static string FileTypePDF {
            get {
                return ResourceManager.GetString("FileTypePDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anthology contributions.
        /// </summary>
        public static string LabelAnthologies {
            get {
                return ResourceManager.GetString("LabelAnthologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Awards.
        /// </summary>
        public static string LabelAwards {
            get {
                return ResourceManager.GetString("LabelAwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to {0}.
        /// </summary>
        public static string LabelBackTo {
            get {
                return ResourceManager.GetString("LabelBackTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binding.
        /// </summary>
        public static string LabelBinding {
            get {
                return ResourceManager.GetString("LabelBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        public static string LabelBook {
            get {
                return ResourceManager.GetString("LabelBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string LabelDelete {
            get {
                return ResourceManager.GetString("LabelDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string LabelDescription {
            get {
                return ResourceManager.GetString("LabelDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag and drop to sort.
        /// </summary>
        public static string LabelDragAndDropToSort {
            get {
                return ResourceManager.GetString("LabelDragAndDropToSort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book editions.
        /// </summary>
        public static string LabelEditions {
            get {
                return ResourceManager.GetString("LabelEditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excerpt.
        /// </summary>
        public static string LabelExcerpt {
            get {
                return ResourceManager.GetString("LabelExcerpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string LabelFileCategory {
            get {
                return ResourceManager.GetString("LabelFileCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string LabelFirstName {
            get {
                return ResourceManager.GetString("LabelFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genre.
        /// </summary>
        public static string LabelGenre {
            get {
                return ResourceManager.GetString("LabelGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show with own page on site.
        /// </summary>
        public static string LabelHasPage {
            get {
                return ResourceManager.GetString("LabelHasPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN.
        /// </summary>
        public static string LabelIsbn {
            get {
                return ResourceManager.GetString("LabelIsbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debut.
        /// </summary>
        public static string LabelIsDebut {
            get {
                return ResourceManager.GetString("LabelIsDebut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For sale.
        /// </summary>
        public static string LabelIsForSale {
            get {
                return ResourceManager.GetString("LabelIsForSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show on site.
        /// </summary>
        public static string LabelIsVisible {
            get {
                return ResourceManager.GetString("LabelIsVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large image.
        /// </summary>
        public static string LabelLargeImage {
            get {
                return ResourceManager.GetString("LabelLargeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LabelLastName {
            get {
                return ResourceManager.GetString("LabelLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LabelLogOut {
            get {
                return ResourceManager.GetString("LabelLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main content.
        /// </summary>
        public static string LabelMainContent {
            get {
                return ResourceManager.GetString("LabelMainContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        public static string LabelNumber {
            get {
                return ResourceManager.GetString("LabelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of pages.
        /// </summary>
        public static string LabelPageCount {
            get {
                return ResourceManager.GetString("LabelPageCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string LabelPerson {
            get {
                return ResourceManager.GetString("LabelPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photographer.
        /// </summary>
        public static string LabelPhotographerCredit {
            get {
                return ResourceManager.GetString("LabelPhotographerCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string LabelPrice {
            get {
                return ResourceManager.GetString("LabelPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review quotes.
        /// </summary>
        public static string LabelQuotes {
            get {
                return ResourceManager.GetString("LabelQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rights holders.
        /// </summary>
        public static string LabelRelations {
            get {
                return ResourceManager.GetString("LabelRelations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release date.
        /// </summary>
        public static string LabelReleaseDate {
            get {
                return ResourceManager.GetString("LabelReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string LabelRole {
            get {
                return ResourceManager.GetString("LabelRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string LabelSave {
            get {
                return ResourceManager.GetString("LabelSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string LabelSelectFile {
            get {
                return ResourceManager.GetString("LabelSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short version.
        /// </summary>
        public static string LabelShortName {
            get {
                return ResourceManager.GetString("LabelShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small image.
        /// </summary>
        public static string LabelSmallImage {
            get {
                return ResourceManager.GetString("LabelSmallImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string LabelSubmit {
            get {
                return ResourceManager.GetString("LabelSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LabelSubmitLogin {
            get {
                return ResourceManager.GetString("LabelSubmitLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle.
        /// </summary>
        public static string LabelSubtitle {
            get {
                return ResourceManager.GetString("LabelSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supporting content.
        /// </summary>
        public static string LabelSupportingContent {
            get {
                return ResourceManager.GetString("LabelSupportingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string LabelTitle {
            get {
                return ResourceManager.GetString("LabelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Translated works.
        /// </summary>
        public static string LabelTranslations {
            get {
                return ResourceManager.GetString("LabelTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string LabelUsername {
            get {
                return ResourceManager.GetString("LabelUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this page can not be displayed.
        /// </summary>
        public static string MessageUnhandledException {
            get {
                return ResourceManager.GetString("MessageUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string PagenameAdmin {
            get {
                return ResourceManager.GetString("PagenameAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bindings.
        /// </summary>
        public static string PagenameBindings {
            get {
                return ResourceManager.GetString("PagenameBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        public static string PagenameBooks {
            get {
                return ResourceManager.GetString("PagenameBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New binding.
        /// </summary>
        public static string PagenameCreateBinding {
            get {
                return ResourceManager.GetString("PagenameCreateBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New book.
        /// </summary>
        public static string PagenameCreateBook {
            get {
                return ResourceManager.GetString("PagenameCreateBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New book edition.
        /// </summary>
        public static string PagenameCreateEdition {
            get {
                return ResourceManager.GetString("PagenameCreateEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New genre.
        /// </summary>
        public static string PagenameCreateGenre {
            get {
                return ResourceManager.GetString("PagenameCreateGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New person.
        /// </summary>
        public static string PagenameCreatePerson {
            get {
                return ResourceManager.GetString("PagenameCreatePerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New rights holder.
        /// </summary>
        public static string PagenameCreateRelation {
            get {
                return ResourceManager.GetString("PagenameCreateRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New role.
        /// </summary>
        public static string PagenameCreateRole {
            get {
                return ResourceManager.GetString("PagenameCreateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New file.
        /// </summary>
        public static string PagenameCreateUpload {
            get {
                return ResourceManager.GetString("PagenameCreateUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit binding.
        /// </summary>
        public static string PagenameEditBinding {
            get {
                return ResourceManager.GetString("PagenameEditBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit book.
        /// </summary>
        public static string PagenameEditBook {
            get {
                return ResourceManager.GetString("PagenameEditBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit book edition.
        /// </summary>
        public static string PagenameEditEdition {
            get {
                return ResourceManager.GetString("PagenameEditEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit genre.
        /// </summary>
        public static string PagenameEditGenre {
            get {
                return ResourceManager.GetString("PagenameEditGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit person.
        /// </summary>
        public static string PagenameEditPerson {
            get {
                return ResourceManager.GetString("PagenameEditPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit rights holder.
        /// </summary>
        public static string PagenameEditRelation {
            get {
                return ResourceManager.GetString("PagenameEditRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit role.
        /// </summary>
        public static string PagenameEditRole {
            get {
                return ResourceManager.GetString("PagenameEditRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string PagenameError {
            get {
                return ResourceManager.GetString("PagenameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genres.
        /// </summary>
        public static string PagenameGenres {
            get {
                return ResourceManager.GetString("PagenameGenres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string PagenameLogIn {
            get {
                return ResourceManager.GetString("PagenameLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        public static string PagenamePersons {
            get {
                return ResourceManager.GetString("PagenamePersons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string PagenameRoles {
            get {
                return ResourceManager.GetString("PagenameRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files.
        /// </summary>
        public static string PagenameUploads {
            get {
                return ResourceManager.GetString("PagenameUploads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forfattere.
        /// </summary>
        public static string SitemenuAuthors {
            get {
                return ResourceManager.GetString("SitemenuAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bøker.
        /// </summary>
        public static string SitemenuBooks {
            get {
                return ResourceManager.GetString("SitemenuBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forside.
        /// </summary>
        public static string SitemenuHome {
            get {
                return ResourceManager.GetString("SitemenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprint CMS.
        /// </summary>
        public static string SystemName {
            get {
                return ResourceManager.GetString("SystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolon Forlag, Postboks 6860 St. Olavs plass, 0130 Oslo, Besøksadresse: Sehestedsgt. 4, 0164 Oslo&lt;br/&gt;Telefon: 22 03 42 02 | &lt;a href=&quot;mailto:redaksjon@kolonforlag.no&quot;&gt;redaksjon@kolonforlag.no&lt;/a&gt;.
        /// </summary>
        public static string SystemSiteFooter {
            get {
                return ResourceManager.GetString("SystemSiteFooter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kolon.
        /// </summary>
        public static string SystemSiteName {
            get {
                return ResourceManager.GetString("SystemSiteName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bytes.
        /// </summary>
        public static string UnitBytesPlural {
            get {
                return ResourceManager.GetString("UnitBytesPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to byte.
        /// </summary>
        public static string UnitBytesSingular {
            get {
                return ResourceManager.GetString("UnitBytesSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kB.
        /// </summary>
        public static string UnitKiloBytesShort {
            get {
                return ResourceManager.GetString("UnitKiloBytesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        public static string UnitMegaBytesShort {
            get {
                return ResourceManager.GetString("UnitMegaBytesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during an AJAX operation. Please reload the page to see its current state..
        /// </summary>
        public static string ValidationAjaxError {
            get {
                return ResourceManager.GetString("ValidationAjaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This element is referenced by others, and can not be deleted.
        /// </summary>
        public static string ValidationElementHasDependenciesAndCanNotBeDeleted {
            get {
                return ResourceManager.GetString("ValidationElementHasDependenciesAndCanNotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file or file is empty.
        /// </summary>
        public static string ValidationEmptyOrNoFile {
            get {
                return ResourceManager.GetString("ValidationEmptyOrNoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file with this name already exists in this category. Delete old file first if you want to replace it..
        /// </summary>
        public static string ValidationFileExists {
            get {
                return ResourceManager.GetString("ValidationFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is too large (max 10 MB).
        /// </summary>
        public static string ValidationFileTooLarge {
            get {
                return ResourceManager.GetString("ValidationFileTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username/password.
        /// </summary>
        public static string ValidationInvalidLogin {
            get {
                return ResourceManager.GetString("ValidationInvalidLogin", resourceCulture);
            }
        }
    }
}
