//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.530
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImprintCMS.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Phrases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Phrases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImprintCMS.App_GlobalResources.Phrases", typeof(Phrases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string FileTypeImage {
            get {
                return ResourceManager.GetString("FileTypeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF.
        /// </summary>
        public static string FileTypePDF {
            get {
                return ResourceManager.GetString("FileTypePDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string LabelDelete {
            get {
                return ResourceManager.GetString("LabelDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string LabelFileCategory {
            get {
                return ResourceManager.GetString("LabelFileCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        public static string LabelLogOut {
            get {
                return ResourceManager.GetString("LabelLogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string LabelPassword {
            get {
                return ResourceManager.GetString("LabelPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string LabelSave {
            get {
                return ResourceManager.GetString("LabelSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string LabelSelectFile {
            get {
                return ResourceManager.GetString("LabelSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string LabelSubmit {
            get {
                return ResourceManager.GetString("LabelSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LabelSubmitLogin {
            get {
                return ResourceManager.GetString("LabelSubmitLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string LabelUsername {
            get {
                return ResourceManager.GetString("LabelUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this page can not be displayed.
        /// </summary>
        public static string MessageUnhandledException {
            get {
                return ResourceManager.GetString("MessageUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string PagenameAdmin {
            get {
                return ResourceManager.GetString("PagenameAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bindings.
        /// </summary>
        public static string PagenameBindings {
            get {
                return ResourceManager.GetString("PagenameBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New binding.
        /// </summary>
        public static string PagenameCreateBinding {
            get {
                return ResourceManager.GetString("PagenameCreateBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New upload.
        /// </summary>
        public static string PagenameCreateUpload {
            get {
                return ResourceManager.GetString("PagenameCreateUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit binding.
        /// </summary>
        public static string PagenameEditBinding {
            get {
                return ResourceManager.GetString("PagenameEditBinding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string PagenameError {
            get {
                return ResourceManager.GetString("PagenameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string PagenameLogIn {
            get {
                return ResourceManager.GetString("PagenameLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploads.
        /// </summary>
        public static string PagenameUploads {
            get {
                return ResourceManager.GetString("PagenameUploads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imprint CMS.
        /// </summary>
        public static string SystemName {
            get {
                return ResourceManager.GetString("SystemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bytes.
        /// </summary>
        public static string UnitBytesPlural {
            get {
                return ResourceManager.GetString("UnitBytesPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to byte.
        /// </summary>
        public static string UnitBytesSingular {
            get {
                return ResourceManager.GetString("UnitBytesSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kB.
        /// </summary>
        public static string UnitKiloBytesShort {
            get {
                return ResourceManager.GetString("UnitKiloBytesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        public static string UnitMegaBytesShort {
            get {
                return ResourceManager.GetString("UnitMegaBytesShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file or file is empty.
        /// </summary>
        public static string ValidationEmptyOrNoFile {
            get {
                return ResourceManager.GetString("ValidationEmptyOrNoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A file with this name already exists in this category. Delete old file first if you want to replace it..
        /// </summary>
        public static string ValidationFileExists {
            get {
                return ResourceManager.GetString("ValidationFileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is too large (max 5 MB).
        /// </summary>
        public static string ValidationFileTooLarge {
            get {
                return ResourceManager.GetString("ValidationFileTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username/password.
        /// </summary>
        public static string ValidationInvalidLogin {
            get {
                return ResourceManager.GetString("ValidationInvalidLogin", resourceCulture);
            }
        }
    }
}
