//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImprintCMS.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SitePhrases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SitePhrases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImprintCMS.App_GlobalResources.SitePhrases", typeof(SitePhrases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nyheter om {0}.
        /// </summary>
        public static string HeadingArticlesAbout {
            get {
                return ResourceManager.GetString("HeadingArticlesAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antologibidrag.
        /// </summary>
        public static string HeadingAuthorAnthologies {
            get {
                return ResourceManager.GetString("HeadingAuthorAnthologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priser.
        /// </summary>
        public static string HeadingAuthorAwards {
            get {
                return ResourceManager.GetString("HeadingAuthorAwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bøker.
        /// </summary>
        public static string HeadingAuthorBooks {
            get {
                return ResourceManager.GetString("HeadingAuthorBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oversettelser.
        /// </summary>
        public static string HeadingAuthorTranslations {
            get {
                return ResourceManager.GetString("HeadingAuthorTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Om {0}.
        /// </summary>
        public static string HeadingBookQuotes {
            get {
                return ResourceManager.GetString("HeadingBookQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flere bilder.
        /// </summary>
        public static string HeadingMoreImages {
            get {
                return ResourceManager.GetString("HeadingMoreImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bøker.
        /// </summary>
        public static string HeadingSearchBooks {
            get {
                return ResourceManager.GetString("HeadingSearchBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forfattere.
        /// </summary>
        public static string HeadingSearchPeople {
            get {
                return ResourceManager.GetString("HeadingSearchPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle bøker.
        /// </summary>
        public static string LabelAllBooks {
            get {
                return ResourceManager.GetString("LabelAllBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilde til artikkelen {0}.
        /// </summary>
        public static string LabelArticleImage {
            get {
                return ResourceManager.GetString("LabelArticleImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Her skal det vises en lydavspiller. Din nettleser kan ikke vise denne..
        /// </summary>
        public static string LabelAudioExcerptPlaceholder {
            get {
                return ResourceManager.GetString("LabelAudioExcerptPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilde av {0}.
        /// </summary>
        public static string LabelAuthorImage {
            get {
                return ResourceManager.GetString("LabelAuthorImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kjøp hos {0}.
        /// </summary>
        public static string LabelBuyFrom {
            get {
                return ResourceManager.GetString("LabelBuyFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kjøp hos ….
        /// </summary>
        public static string LabelBuyThroughExternalStores {
            get {
                return ResourceManager.GetString("LabelBuyThroughExternalStores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avbryt.
        /// </summary>
        public static string LabelCancel {
            get {
                return ResourceManager.GetString("LabelCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omslaget til {0}.
        /// </summary>
        public static string LabelCoverImage {
            get {
                return ResourceManager.GetString("LabelCoverImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. utgave.
        /// </summary>
        public static string LabelEdition {
            get {
                return ResourceManager.GetString("LabelEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. utgave, {1}.
        /// </summary>
        public static string LabelEditionAndYear {
            get {
                return ResourceManager.GetString("LabelEditionAndYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-post.
        /// </summary>
        public static string LabelEmail {
            get {
                return ResourceManager.GetString("LabelEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utdrag fra {0} (pdf).
        /// </summary>
        public static string LabelExcerpt {
            get {
                return ResourceManager.GetString("LabelExcerpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN {0}.
        /// </summary>
        public static string LabelIsbn {
            get {
                return ResourceManager.GetString("LabelIsbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debut.
        /// </summary>
        public static string LabelIsDebut {
            get {
                return ResourceManager.GetString("LabelIsDebut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utkommet.
        /// </summary>
        public static string LabelIsReleased {
            get {
                return ResourceManager.GetString("LabelIsReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stort omslag.
        /// </summary>
        public static string LabelLargeCover {
            get {
                return ResourceManager.GetString("LabelLargeCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stort portrett.
        /// </summary>
        public static string LabelLargePortrait {
            get {
                return ResourceManager.GetString("LabelLargePortrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ?.
        /// </summary>
        public static string LabelLegendPlaceholder {
            get {
                return ResourceManager.GetString("LabelLegendPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navn.
        /// </summary>
        public static string LabelName {
            get {
                return ResourceManager.GetString("LabelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neste.
        /// </summary>
        public static string LabelNext {
            get {
                return ResourceManager.GetString("LabelNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikke i salg.
        /// </summary>
        public static string LabelNotForSale {
            get {
                return ResourceManager.GetString("LabelNotForSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto: {0}.
        /// </summary>
        public static string LabelPhotoCredit {
            get {
                return ResourceManager.GetString("LabelPhotoCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tilbake.
        /// </summary>
        public static string LabelPrevious {
            get {
                return ResourceManager.GetString("LabelPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last ned.
        /// </summary>
        public static string LabelProceedToDownload {
            get {
                return ResourceManager.GetString("LabelProceedToDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Søk.
        /// </summary>
        public static string LabelSearch {
            get {
                return ResourceManager.GetString("LabelSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Søk etter bok eller forfatter.
        /// </summary>
        public static string LabelSearchPlaceholder {
            get {
                return ResourceManager.GetString("LabelSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen treff.
        /// </summary>
        public static string LabelSearchResultEmpty {
            get {
                return ResourceManager.GetString("LabelSearchResultEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Del på Twitter.
        /// </summary>
        public static string LabelShareOnTwitter {
            get {
                return ResourceManager.GetString("LabelShareOnTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommer.
        /// </summary>
        public static string LabelToBeReleased {
            get {
                return ResourceManager.GetString("LabelToBeReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forfattere.
        /// </summary>
        public static string MenuAuthors {
            get {
                return ResourceManager.GetString("MenuAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bøker.
        /// </summary>
        public static string MenuBooks {
            get {
                return ResourceManager.GetString("MenuBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forside.
        /// </summary>
        public static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Søk.
        /// </summary>
        public static string MenuSearch {
            get {
                return ResourceManager.GetString("MenuSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to medio.
        /// </summary>
        public static string UnitMonthMedio {
            get {
                return ResourceManager.GetString("UnitMonthMedio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to primo.
        /// </summary>
        public static string UnitMonthPrimo {
            get {
                return ResourceManager.GetString("UnitMonthPrimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ultimo.
        /// </summary>
        public static string UnitMonthUltimo {
            get {
                return ResourceManager.GetString("UnitMonthUltimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} s.
        /// </summary>
        public static string UnitPages {
            get {
                return ResourceManager.GetString("UnitPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F2} kr.
        /// </summary>
        public static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
    }
}
