//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.544
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImprintCMS.Models {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SitePhrases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SitePhrases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ImprintCMS.App_GlobalResources.SitePhrases", typeof(SitePhrases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antologibidrag.
        /// </summary>
        public static string HeadingAuthorAnthologies {
            get {
                return ResourceManager.GetString("HeadingAuthorAnthologies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priser.
        /// </summary>
        public static string HeadingAuthorAwards {
            get {
                return ResourceManager.GetString("HeadingAuthorAwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bøker.
        /// </summary>
        public static string HeadingAuthorBooks {
            get {
                return ResourceManager.GetString("HeadingAuthorBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oversettelser.
        /// </summary>
        public static string HeadingAuthorTranslations {
            get {
                return ResourceManager.GetString("HeadingAuthorTranslations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Om {0}.
        /// </summary>
        public static string HeadingBookQuotes {
            get {
                return ResourceManager.GetString("HeadingBookQuotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bøker.
        /// </summary>
        public static string HeadingSearchBooks {
            get {
                return ResourceManager.GetString("HeadingSearchBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forfattere.
        /// </summary>
        public static string HeadingSearchPeople {
            get {
                return ResourceManager.GetString("HeadingSearchPeople", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kjøp.
        /// </summary>
        public static string LabelAddToShop {
            get {
                return ResourceManager.GetString("LabelAddToShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilde av {0}.
        /// </summary>
        public static string LabelAuthorImage {
            get {
                return ResourceManager.GetString("LabelAuthorImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omslaget til {0}.
        /// </summary>
        public static string LabelCoverImage {
            get {
                return ResourceManager.GetString("LabelCoverImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}. utgave.
        /// </summary>
        public static string LabelEdition {
            get {
                return ResourceManager.GetString("LabelEdition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utdrag fra {0} (pdf).
        /// </summary>
        public static string LabelExcerpt {
            get {
                return ResourceManager.GetString("LabelExcerpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISBN {0}.
        /// </summary>
        public static string LabelIsbn {
            get {
                return ResourceManager.GetString("LabelIsbn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utkommet.
        /// </summary>
        public static string LabelIsReleased {
            get {
                return ResourceManager.GetString("LabelIsReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ikke i salg.
        /// </summary>
        public static string LabelNotForSale {
            get {
                return ResourceManager.GetString("LabelNotForSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto: {0}.
        /// </summary>
        public static string LabelPhotoCredit {
            get {
                return ResourceManager.GetString("LabelPhotoCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Søk.
        /// </summary>
        public static string LabelSearch {
            get {
                return ResourceManager.GetString("LabelSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Søk etter bok eller forfatter.
        /// </summary>
        public static string LabelSearchPlaceholder {
            get {
                return ResourceManager.GetString("LabelSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen treff.
        /// </summary>
        public static string LabelSearchResultEmpty {
            get {
                return ResourceManager.GetString("LabelSearchResultEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Del på Twitter.
        /// </summary>
        public static string LabelShareOnTwitter {
            get {
                return ResourceManager.GetString("LabelShareOnTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frakt på kr {0} tilkommer på ordre opp til kr {1}..
        /// </summary>
        public static string LabelShopDisplayDistributionCost {
            get {
                return ResourceManager.GetString("LabelShopDisplayDistributionCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du har ingen bøker i handlekurven.
        /// </summary>
        public static string LabelShopEmpty {
            get {
                return ResourceManager.GetString("LabelShopEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gratis frakt på alle ordre over kr {0}..
        /// </summary>
        public static string LabelShopNoDistributionCost {
            get {
                return ResourceManager.GetString("LabelShopNoDistributionCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tøm handlekurv.
        /// </summary>
        public static string LabelShopRemoveAll {
            get {
                return ResourceManager.GetString("LabelShopRemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjern.
        /// </summary>
        public static string LabelShopRemoveOne {
            get {
                return ResourceManager.GetString("LabelShopRemoveOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommer.
        /// </summary>
        public static string LabelToBeReleased {
            get {
                return ResourceManager.GetString("LabelToBeReleased", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forfattere.
        /// </summary>
        public static string MenuAuthors {
            get {
                return ResourceManager.GetString("MenuAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bøker.
        /// </summary>
        public static string MenuBooks {
            get {
                return ResourceManager.GetString("MenuBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontakt oss.
        /// </summary>
        public static string MenuContact {
            get {
                return ResourceManager.GetString("MenuContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forside.
        /// </summary>
        public static string MenuHome {
            get {
                return ResourceManager.GetString("MenuHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Søk.
        /// </summary>
        public static string MenuSearch {
            get {
                return ResourceManager.GetString("MenuSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kjøp.
        /// </summary>
        public static string MenuShop {
            get {
                return ResourceManager.GetString("MenuShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to medio.
        /// </summary>
        public static string UnitMonthMedio {
            get {
                return ResourceManager.GetString("UnitMonthMedio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to premio.
        /// </summary>
        public static string UnitMonthPremio {
            get {
                return ResourceManager.GetString("UnitMonthPremio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ultimo.
        /// </summary>
        public static string UnitMonthUltimo {
            get {
                return ResourceManager.GetString("UnitMonthUltimo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sider.
        /// </summary>
        public static string UnitPagesPlural {
            get {
                return ResourceManager.GetString("UnitPagesPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to side.
        /// </summary>
        public static string UnitPagesSingular {
            get {
                return ResourceManager.GetString("UnitPagesSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} kr.
        /// </summary>
        public static string UnitPrice {
            get {
                return ResourceManager.GetString("UnitPrice", resourceCulture);
            }
        }
    }
}
